#!/usr/bin/env bun
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { DIST_CATALOG, DIST_DIR, DIST_HASH, buildCatalog } from "../src/index";

/** dist/catalog.embedded.ts — a generated TS module holding the canonical
 * bytes + hash as string literals. src/embedded.ts imports it so the bundler
 * (`bun build --compile`) embeds the catalog into the server binary without any
 * import-attribute or resolveJsonModule typing friction. Generated, checked in,
 * and drift-guarded exactly like dist/catalog.json. */
const DIST_EMBEDDED_TS = join(DIST_DIR, "catalog.embedded.ts");

function emitEmbeddedModule(canonicalJson: string, hash: string): string {
	// JSON.stringify produces a safe, escaped TS/JS string literal.
	return `// GENERATED by core/catalog/scripts/build.ts — do not edit.
// The canonical catalog bytes + hash, embedded for \`bun build --compile\`.
export const CATALOG_JSON = ${JSON.stringify(canonicalJson)};
export const CATALOG_HASH = ${JSON.stringify(hash)};
`;
}

/**
 * Catalog build CLI. Validates + lints data/, and on success canonicalizes to
 * dist/catalog.json + dist/catalog.hash. Exits non-zero (and writes nothing)
 * on any schema or lint failure, so it gates CI and `catalog:check`.
 */
function main(): number {
	const { report, canonicalJson, hash } = buildCatalog();

	if (!report.ok) {
		console.error("✗ catalog build failed\n");
		if (report.schemaErrors.length > 0) {
			console.error("Schema errors:");
			for (const { file, error } of report.schemaErrors) {
				console.error(`  ${file}\n    ${error}`);
			}
		}
		if (report.lintIssues.length > 0) {
			console.error("Lint issues:");
			for (const issue of report.lintIssues) {
				console.error(`  ${issue.path}\n    ${issue.message}`);
			}
		}
		return 1;
	}

	if (!canonicalJson || !hash) {
		console.error("✗ catalog build produced no output despite an ok report");
		return 1;
	}

	mkdirSync(DIST_DIR, { recursive: true });
	writeFileSync(DIST_CATALOG, canonicalJson);
	// Trailing newline so the hash file is a well-formed text line.
	writeFileSync(DIST_HASH, `${hash}\n`);
	writeFileSync(DIST_EMBEDDED_TS, emitEmbeddedModule(canonicalJson, hash));

	const sizeKb = (Buffer.byteLength(canonicalJson, "utf8") / 1024).toFixed(1);
	console.log(`✓ catalog built — ${sizeKb} KiB, sha256 ${hash}`);
	return 0;
}

process.exit(main());
