import { type Catalog, catalogSchema } from "@core/types";
// dist/catalog.embedded.ts is generated by scripts/build.ts and holds the
// canonical catalog bytes + hash as plain string literals. Importing it (rather
// than reading dist/ from the filesystem) lets `bun build --compile` embed the
// catalog directly into the server binary — the compiled server ships with its
// catalog and needs no sidecar files. Using a generated .ts module (instead of
// `import ... with { type: "text" }`) sidesteps import-attribute and
// resolveJsonModule typing friction.
import { CATALOG_HASH, CATALOG_JSON } from "../dist/catalog.embedded";
import { hashCatalog } from "./canonical";

export type EmbeddedCatalog = {
	catalog: Catalog;
	/** The exact canonical JSON bytes (for shipping over the wire on welcome). */
	canonicalJson: string;
	hash: string;
};

/**
 * The catalog embedded at build time. Validates the declared hash against the
 * embedded bytes (a mismatch means dist was stale when the module was generated).
 */
export function loadEmbeddedCatalog(): EmbeddedCatalog {
	const canonicalJson = CATALOG_JSON;
	const actualHash = hashCatalog(canonicalJson);
	if (CATALOG_HASH !== actualHash) {
		throw new Error(
			`embedded CATALOG_HASH (${CATALOG_HASH}) does not match CATALOG_JSON (${actualHash}) — rebuild the catalog`,
		);
	}
	const catalog = catalogSchema.parse(JSON.parse(canonicalJson));
	return { catalog, canonicalJson, hash: actualHash };
}
